---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
    branches:
      - main

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The second workflow'
